
name: Android CI - Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Make gradlew executable if present
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi
      - name: Build debug APK
        run: |
          if [ -f ./gradlew ]; then ./gradlew assembleDebug --no-daemon; else gradle assembleDebug --no-daemon; fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk-${ github.run_id }
          path: app/build/outputs/apk/debug/*.apk
